version: '3.8'
services:
  scraper:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 6080:6080
      - 3000:3000
    volumes:
      - .:/develop/
      - ./browser-profile:/app/browser-profile
    working_dir: /app
    shm_size: '1gb'
